/**
 * Scryfall card-symbol SVGs, bundled under `public/mana/`.
 *
 * Generated from https://api.scryfall.com/symbology. Filenames are usually the
 * symbol with slashes removed, but not always ({\u00bd} and {\u221e} differ), so the
 * mapping is explicit rather than derived.
 *
 * Keys are the symbol without braces: "W", "2/U", "W/P".
 */
export const MANA_SYMBOL_FILES: Record<string, string> = {
  "0": "0.svg",
  "1": "1.svg",
  "2": "2.svg",
  "3": "3.svg",
  "4": "4.svg",
  "5": "5.svg",
  "6": "6.svg",
  "7": "7.svg",
  "8": "8.svg",
  "9": "9.svg",
  "A": "A.svg",
  "B": "B.svg",
  "C": "C.svg",
  "D": "D.svg",
  "E": "E.svg",
  "G": "G.svg",
  "H": "H.svg",
  "L": "L.svg",
  "P": "P.svg",
  "Q": "Q.svg",
  "R": "R.svg",
  "S": "S.svg",
  "T": "T.svg",
  "U": "U.svg",
  "W": "W.svg",
  "X": "X.svg",
  "Y": "Y.svg",
  "Z": "Z.svg",
  "½": "HALF.svg",
  "∞": "INFINITY.svg",
  "10": "10.svg",
  "11": "11.svg",
  "12": "12.svg",
  "13": "13.svg",
  "14": "14.svg",
  "15": "15.svg",
  "16": "16.svg",
  "17": "17.svg",
  "18": "18.svg",
  "19": "19.svg",
  "20": "20.svg",
  "HR": "HR.svg",
  "HW": "HW.svg",
  "PW": "PW.svg",
  "TK": "TK.svg",
  "100": "100.svg",
  "2/B": "2B.svg",
  "2/G": "2G.svg",
  "2/R": "2R.svg",
  "2/U": "2U.svg",
  "2/W": "2W.svg",
  "B/G": "BG.svg",
  "B/P": "BP.svg",
  "B/R": "BR.svg",
  "C/B": "CB.svg",
  "C/G": "CG.svg",
  "C/P": "CP.svg",
  "C/R": "CR.svg",
  "C/U": "CU.svg",
  "C/W": "CW.svg",
  "G/P": "GP.svg",
  "G/U": "GU.svg",
  "G/W": "GW.svg",
  "R/G": "RG.svg",
  "R/P": "RP.svg",
  "R/W": "RW.svg",
  "U/B": "UB.svg",
  "U/P": "UP.svg",
  "U/R": "UR.svg",
  "W/B": "WB.svg",
  "W/P": "WP.svg",
  "W/U": "WU.svg",
  "B/G/P": "BGP.svg",
  "B/R/P": "BRP.svg",
  "CHAOS": "CHAOS.svg",
  "G/U/P": "GUP.svg",
  "G/W/P": "GWP.svg",
  "R/G/P": "RGP.svg",
  "R/W/P": "RWP.svg",
  "U/B/P": "UBP.svg",
  "U/R/P": "URP.svg",
  "W/B/P": "WBP.svg",
  "W/U/P": "WUP.svg",
  "1000000": "1000000.svg",
};

/** Resolve a symbol (without braces) to its bundled SVG url, if we have one. */
export function manaSymbolUrl(symbol: string): string | null {
  const file = MANA_SYMBOL_FILES[symbol.toUpperCase()] ?? MANA_SYMBOL_FILES[symbol];
  return file ? `/mana/${file}` : null;
}
